### ISSUE TITLE
Unable to run django-ide with django version 1.8.4

### ISSUE THREAD

**Issue by achatte** [lusob/django-ide#8]
I was unable to run the django-ide using django version 1.8.4. Any thoughts?

**Comment by lusob** [comment]
Hi Achatte, currently I've no time to dedicate to the project but any
pull-request will be revised and merged. Thanks for your support!

On Thu, Mar 24, 2016 at 1:22 PM, achatte <notifications@github.com> wrote:

> I was unable to run the django-ide using django version 1.8.4. Any
> thoughts?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lusob/django-ide/issues/8>
>



-- 
Un saludo,
Luis
